# Generated by Django 4.2.5 on 2023-09-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_amount_product_price_product_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amount',
        ),
    ]
