# Generated by Django 4.2.5 on 2023-09-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amounts',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='prices',
        ),
    ]
